### PR TITLE
Support DJ bios

### LINKED ISSUE #16: Support DJ Bios
DJs have the ability to create bios and post them to the site. It'd be pretty dope if you could tap on that DJs picture in the app and have that same bio come up.

What it looks like on the site:

screen shot 2017-04-05 at 10 01 31 am

You'd probably be interested in [this api route](https://github.com/uclaradio/uclaradio/wiki/The-API#apidjid-get).

### PR DESCRIPTION
**Pull request by bsakhuja**
# Display DJ Bios

## Types of changes

- [ ] Bugfix (change which fixes an issue)
- [x] New feature (change which adds functionality)
- [ ] Refactor (change which changes the codebase without affecting its external behavior)
- [ ] Non-breaking change (fix or feature that would causes existing functionality to work as expected)
- [ ] Breaking change (fix or feature that would cause existing functionality to __not__ work as expected)

## Purpose

Resolves #16 

## Approach

- Performed 'pod update'
- Implemented pod 'Presentr' to create a popup display of a new DJPopupViewController which displays the DJ name, DJ real name, and DJ biography.  
- Modified DJ.swift to support the retrieval of DJ bios.
- Be aware that 'Presentr' is compiled using the Swift 4 compiler.  All other pods are still using some version of Swift 3.  This can be changed by selecting the Pods project and navigating to any of the targets and searching for 'Swift Language Version.'  You should be able to change the version of Swift for each of the pods as necessary.

## Screenshot(s) 

img_8618

## Checklist

- [x] My branch follows the branch naming scheme of UCLA Radio, and can merge into `master` without error.
- [x] My code follows the code style of this project, and I have linted it to confirm this.
- [ ] I have added tests that prove my fix is effective or that my feature works.
- [x] My change requires a change to the documentation and I have updated the documentation accordingly.
- [ ] All new and existing tests passed.

## Platform

__Operating System:__ iOS 11.2 beta 3

### CODE REVIEW

**Comment by nathunsmitty** [comment]
Very cool!!!! 😍 Could we maybe add a DJ's photo in the popup?

**Comment by bsakhuja** [comment]
DJ bio's with images now fully functional!

**Comment by bsakhuja** [comment]
Updated screenshots:
img_8732
img_8733

**Comment by nathunsmitty** [comment]
Awesome! 💯

**Pull request merged**
