### PR TITLE
Swift 4 and iPhone X support

### LINKED ISSUE #32: Upgrade to Swift 4 and iPhone X Optimization

### PR DESCRIPTION
**Pull request by bsakhuja**
Upgraded to Swift 4 and added iPhone X support

## Types of changes

- [ ] Bugfix (change which fixes an issue)
- [ ] New feature (change which adds functionality)
- [x] Refactor (change which changes the codebase without affecting its external behavior)
- [x] Non-breaking change (fix or feature that would cause existing functionality to work as expected)
- [ ] Breaking change (fix or feature that would cause existing functionality to __not__ work as expected)

## Purpose

- Resolves /pods in .gitignore issue mentioned in #24 
- Resolves #32 

## Approach

- Upgraded from Swift 3 to 4 as Swift 4 is the most recent version. 
- Optimized iPhone X UI (the pulltab on the sliding view controller was partially hidden).
- Updated pods
- /pods folder is no longer in .gitignore
- Our app is now compatible with Swift 4 and looks good on iPhone X!

## Learning

[Swift 3 to 4 migration](https://swift.org/migration-guide-swift4/)

## Screenshot(s) 

screen shot 2018-02-04 at 6 58 49 pm

## Checklist

- [x] My branch follows the branch naming scheme of UCLA Radio, and can merge into `master` without error.
- [x] My code follows the code style of this project, and I have linted it to confirm this.
- [x] I have added tests that prove my fix is effective or that my feature works.
- [x] My change requires a change to the documentation and I have updated the documentation accordingly.
- [x] All new and existing tests passed.

## Platform

__Operating System:__ 10.13.4 beta 
__Xcode Version:__  9.3 beta (9Q98q)
__iOS Version:__ 11.3 beta

### CODE REVIEW

**Comment by nathunsmitty** [comment]
Hey @bsakhuja! Sorry it's taken me so long to getting around to reviewing this; midterms have not been fun 🙁. I'm getting a `Value of type '[Show?]' has no member 'compactMap'` error in this function in `NotificationViewController.swift`:
```swift
@objc func commitEdit() {
        if tableView.isEditing {
            // delete notifications for selected shows
            let selectedRows = tableView.indexPathsForSelectedRows ?? []
            let selectedShows: [Show] = selectedRows.map { indexPath in
                notificationSchedule?.showForIndexPath(indexPath)
                }.compactMap({$0})
            NotificationManager.sharedInstance.removeAllNotificationsForShows(selectedShows)
            notificationSchedule?.removeShows(selectedShows)
            tableView.deleteRows(at: selectedRows, with: .fade)
        }
        toggleEdit()
    }
```

Here's a screenshot for reference:

screen shot 2018-02-10 at 2 30 52 pm

Any idea why this is happening/how I can fix it?

**Comment by bsakhuja** [comment]
I believe this has something to do with the Xcode 9.3 beta. The instance method .compactMap is only available on Xcode 9.3+ according to the [documentation](
https://developer.apple.com/documentation/swift/array/2950938-compactmap).  I used the beta to do the Swift 3 to 4 migration so I could test it on my phone running the iOS beta.

Do you have access to the beta or should we wait to merge or is there another solution?

**Comment by nathunsmitty** [comment]
Hmm I'd like to stick to stable features just for a more consistent development experience among all of us and in case Apple ends up changing anything before they release Xcode 9.3. It looks like [`compatMap`](https://developer.apple.com/documentation/swift/array/2950938-compactmap) is really just the renaming of [`flatMap`](https://developer.apple.com/documentation/swift/array/2903427-flatmap); how would you feel about just using `flatMap` for now and maybe sticking a `// TODO:` on there to note that we should change it when iOS 11.3 is out?

Other than that, this PR looks gucci to me! I think we're ready to release an app store update after this is merged!

**Comment by bsakhuja** [comment]
Sounds good to me! Changes submitted!

**Pull request merged**
